name: Publish Documentation
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: packages/paperclip-website
jobs:
  publish-documentation:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: yarn install
      - run: yarn run build
      - run: yarn run link
      - name: Build Pages
        run: |
          yarn run publish:documentation
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
