name: Publish Documentation
on:
  push:
    branches:
      - master
jobs:
  publish-documentation:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: npm install
      - run: npm run build
        env:
          NODE_ENV: "production"
      - run: npm run link
      - name: Release to GitHub Pages
        run: |
          git config --global user.email "craig.j.condon@gmail.com"
          git config --global user.name "crcn"
          npm run publish:documentation
        env:
          USE_SSH: true
          GIT_USER: crcn
